spring:
  application:
    name: xueyuanhui-backend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL

server:
  port: 8080

qiniu:
  access-key: zfc9y0LL6rUe5b6dz0c43yOx7cKOxtHn4bON76rz
  secret-key: yoJYJH0AnqKFFcSVJUONwA-OSxwP4jzFvAlefJwL
  bucket: edwell-k12
  domain: https://oss.gut9.cn/

jwt:
  secret: XueYuanHuiSuperSecretKeyForJwtAuthenticationWhichShouldBeLongEnough2024
  expiration: 604800000 # 7天
